### ISSUE TITLE
Question on code and training time

### ISSUE THREAD

**Issue by dlsrbgg33** [shiml20/FlowTurbo#2]
Thank you for your great work.

I have two questions as below:

1.  VAE decoding seems to be redundantly implemented in those two lines: [L143](https://github.com/shiml20/FlowTurbo/blob/696bc1151bea2052c780ed4f3916ae81a275e825/sample_ddp_feature.py#L143) and [L588](https://github.com/shiml20/FlowTurbo/blob/696bc1151bea2052c780ed4f3916ae81a275e825/models_assemble.py#L588
).
2. Did you run all 50 epochs to get the best FID?

I hope you can answer to my questions.
Thank you in advance.

**Comment by shiml20** [comment]
> Thank you for your great work.
> 
> I have two questions as below:
> 
> 1. VAE decoding seems to be redundantly implemented in those two lines: [L143](https://github.com/shiml20/FlowTurbo/blob/696bc1151bea2052c780ed4f3916ae81a275e825/sample_ddp_feature.py#L143) and [L588](https://github.com/shiml20/FlowTurbo/blob/696bc1151bea2052c780ed4f3916ae81a275e825/models_assemble.py#L588).
> 2. Did you run all 50 epochs to get the best FID?
> 
> I hope you can answer to my questions. Thank you in advance.

For the first question:
Thank you very much for your careful review of our code. We appreciate you identifying the bug. This is redundant implementation for VAE decoder. We have fixed it in the new version code.

For the second question:
We did not run all 50 epochs to get the best FID. You can find the detailed training setting of SiT Refiner in our paper: Appendix Part C Implementation Details. https://arxiv.org/pdf/2409.18128

**Comment by dlsrbgg33** [comment]
Thank you for your quick reply.

I have another question toward evaluation.
You are using below command to obtain inception features of 50k samples from pretrained model.

torchrun --nnodes=1 --nproc_per_node=N sample_ddp_feature.py \
    --vae_ckpt vae-ema \
    --predictor_ckpt SiT-XL-2-256x256.pt \
    --refiner_ckpt SiT-XL-2-Refiner.pt \
    --num_fid_samples 60 --per_proc_batch_size 20 --cfg_scale 1.5 \
    --tag TEST ;\

But, it looks like it is not generating 50k samples.
Could you let me know how I can get the final FID score?

**Comment by dlsrbgg33** [comment]
Thank you for your quick reply!
