### ISSUE TITLE
Lumina-Next-T2I ckpt

### ISSUE THREAD

**Issue by ultranity** [shiml20/FlowTurbo#3]
Thanks for sharing this work!

The paper also reported qualitative results of high-resolution text-to-image generation by applying FlowTurbo to the newly released flow-based model Lumina-Next-T2I, but currently it seems that the repo only provides code&ckpt for SiT? 

Since SiT is not focused on text guilded generation, InstaFlow/Lumina-Next-T2I/Flux will be much more attractable. Is there any plan/schedule to release the impl for Lumina-Next-T2I/Flux for evalutations?

**Comment by shiml20** [comment]
Thank you for your interest in our work. We have currently open-sourced our SiT-based model to facilitate academic communication. We will share the InstaFlow code in the near future. And you can also use our method to train your own model !

> Thanks for sharing this work!
> 
> The paper also reported qualitative results of high-resolution text-to-image generation by applying FlowTurbo to the newly released flow-based model Lumina-Next-T2I, but currently it seems that the repo only provides code&ckpt for SiT?
> 
> Since SiT is not focused on text guilded generation, InstaFlow/Lumina-Next-T2I/Flux will be much more attractable. Is there any plan/schedule to release the impl for Lumina-Next-T2I/Flux for evalutations?

Thank you for your interest in our work. We have currently open-sourced our SiT-based model to facilitate academic communication. We will share the InstaFlow code in the near future. And you can also use our method to train your own model !
